language: dart
dart:
  - stable
os:
  - linux
  - osx
sudo: false
addons:
  # chrome: stable
  apt:
    sources:
      - ubuntu-toolchain-r-test # you need this source to get the right version of libstdc++6
    packages:
      - libstdc++6
      - fonts-droid
install:
  - echo 'Avoid default Travis CI install step' # this is to avoid an error with pub in Travis
before_script:
  - ulimit -S -n 2048
  - cd ..
  - git clone --single-branch --branch v1.2.1 https://github.com/flutter/flutter.git
  - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
  - flutter doctor
matrix:
  include:
    - env: NAME="Analyze"
    - env: NAME="Test"
script:
  - cd $TRAVIS_BUILD_DIR
  - flutter packages get
  - if [ $NAME == "Test" ]; then
      flutter test;
    fi
  - if [ $NAME == "Analyze" ]; then
      flutter analyze;
    fi
cache:
  directories:
    - ~/.pub-cache