language: dart
dart:
  - stable
os:
  - linux
  - osx
sudo: false
addons:
  # chrome: stable
  apt:
    sources:
      - ubuntu-toolchain-r-test # you need this source to get the right version of libstdc++6
    packages:
      - libstdc++6
      - fonts-droid
install:
  - echo 'Avoid default Travis CI install step' # this is to avoid an error with pub in Travis
before_script:
  - ulimit -S -n 2048
  - cd ..
  - git clone --single-branch --branch v1.5.4-hotfix.2 https://github.com/flutter/flutter.git
  - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
  - flutter doctor
script:
  - cd $TRAVIS_BUILD_DIR
  - flutter packages get
  - flutter test
  - flutter analyze
